/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuiltForRouteImport } from './routes/built-for'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOrgRouteImport } from './routes/onboarding/org'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSuccessRouteImport } from './routes/_auth/success'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppOrgRouteImport } from './routes/_app/org'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppEscrowRouteImport } from './routes/_app/escrow'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdvisoryRouteImport } from './routes/_app/advisory'
import { Route as OnboardingAccountTypeIndexRouteImport } from './routes/onboarding/account-type/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/organization/index'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox/index'
import { Route as AppCirclesIndexRouteImport } from './routes/_app/circles/index'
import { Route as CompaniesInvitationsAcceptRouteImport } from './routes/companies.invitations.accept'
import { Route as AuthVendorVerifyRouteImport } from './routes/_auth/vendor/verify'
import { Route as AuthVendorRegisterRouteImport } from './routes/_auth/vendor/register'
import { Route as AuthVendorLoginRouteImport } from './routes/_auth/vendor/login'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppOrganizationTeamRouteImport } from './routes/_app/organization/team'
import { Route as AppInboxNnarksAiRouteImport } from './routes/_app/inbox/nnarks-ai'
import { Route as AppInboxAiRouteImport } from './routes/_app/inbox/ai'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/modules.lazy').then((d) => d.Route))
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/financials.lazy').then((d) => d.Route))
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/features.lazy').then((d) => d.Route))
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faqs.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const BuiltForRoute = BuiltForRouteImport.update({
  id: '/built-for',
  path: '/built-for',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/built-for.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrgRoute = OnboardingOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppEscrowRoute = AppEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisoryRoute = AppAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingAccountTypeIndexRoute =
  OnboardingAccountTypeIndexRouteImport.update({
    id: '/account-type/',
    path: '/account-type/',
    getParentRoute: () => OnboardingRoute,
  } as any).lazy(() =>
    import('./routes/onboarding/account-type/index.lazy').then((d) => d.Route),
  )
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppCirclesIndexRoute = AppCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => AppRoute,
} as any)
const CompaniesInvitationsAcceptRoute =
  CompaniesInvitationsAcceptRouteImport.update({
    id: '/companies/invitations/accept',
    path: '/companies/invitations/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVendorVerifyRoute = AuthVendorVerifyRouteImport.update({
  id: '/vendor/verify',
  path: '/vendor/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVendorRegisterRoute = AuthVendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVendorLoginRoute = AuthVendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationTeamRoute = AppOrganizationTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppInboxNnarksAiRoute = AppInboxNnarksAiRouteImport.update({
  id: '/nnarks-ai',
  path: '/nnarks-ai',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInboxAiRoute = AppInboxAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppInboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-for': typeof BuiltForRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/financials': typeof FinancialsRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/advisory': typeof AppAdvisoryRoute
  '/dashboard': typeof AppDashboardRoute
  '/escrow': typeof AppEscrowRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/org': typeof AppOrgRoute
  '/organization': typeof AppOrganizationRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/success': typeof AuthSuccessRoute
  '/verify': typeof AuthVerifyRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/inbox/ai': typeof AppInboxAiRoute
  '/inbox/nnarks-ai': typeof AppInboxNnarksAiRoute
  '/organization/team': typeof AppOrganizationTeamRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/vendor/login': typeof AuthVendorLoginRoute
  '/vendor/register': typeof AuthVendorRegisterRoute
  '/vendor/verify': typeof AuthVendorVerifyRoute
  '/companies/invitations/accept': typeof CompaniesInvitationsAcceptRoute
  '/circles/': typeof AppCirclesIndexRoute
  '/inbox/': typeof AppInboxIndexRoute
  '/organization/': typeof AppOrganizationIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/onboarding/account-type/': typeof OnboardingAccountTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-for': typeof BuiltForRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/financials': typeof FinancialsRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/advisory': typeof AppAdvisoryRoute
  '/dashboard': typeof AppDashboardRoute
  '/escrow': typeof AppEscrowRoute
  '/org': typeof AppOrgRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/success': typeof AuthSuccessRoute
  '/verify': typeof AuthVerifyRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/inbox/ai': typeof AppInboxAiRoute
  '/inbox/nnarks-ai': typeof AppInboxNnarksAiRoute
  '/organization/team': typeof AppOrganizationTeamRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/vendor/login': typeof AuthVendorLoginRoute
  '/vendor/register': typeof AuthVendorRegisterRoute
  '/vendor/verify': typeof AuthVendorVerifyRoute
  '/companies/invitations/accept': typeof CompaniesInvitationsAcceptRoute
  '/circles': typeof AppCirclesIndexRoute
  '/inbox': typeof AppInboxIndexRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/onboarding/account-type': typeof OnboardingAccountTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/built-for': typeof BuiltForRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/financials': typeof FinancialsRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_app/advisory': typeof AppAdvisoryRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escrow': typeof AppEscrowRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/org': typeof AppOrgRoute
  '/_app/organization': typeof AppOrganizationRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/success': typeof AuthSuccessRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/_app/inbox/ai': typeof AppInboxAiRoute
  '/_app/inbox/nnarks-ai': typeof AppInboxNnarksAiRoute
  '/_app/organization/team': typeof AppOrganizationTeamRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_auth/vendor/login': typeof AuthVendorLoginRoute
  '/_auth/vendor/register': typeof AuthVendorRegisterRoute
  '/_auth/vendor/verify': typeof AuthVendorVerifyRoute
  '/companies/invitations/accept': typeof CompaniesInvitationsAcceptRoute
  '/_app/circles/': typeof AppCirclesIndexRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/onboarding/account-type/': typeof OnboardingAccountTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/built-for'
    | '/contact'
    | '/faqs'
    | '/features'
    | '/financials'
    | '/modules'
    | '/onboarding'
    | '/advisory'
    | '/dashboard'
    | '/escrow'
    | '/inbox'
    | '/org'
    | '/organization'
    | '/login'
    | '/register'
    | '/success'
    | '/verify'
    | '/onboarding/org'
    | '/inbox/ai'
    | '/inbox/nnarks-ai'
    | '/organization/team'
    | '/projects/$projectId'
    | '/vendor/login'
    | '/vendor/register'
    | '/vendor/verify'
    | '/companies/invitations/accept'
    | '/circles/'
    | '/inbox/'
    | '/organization/'
    | '/projects/'
    | '/onboarding/account-type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/built-for'
    | '/contact'
    | '/faqs'
    | '/features'
    | '/financials'
    | '/modules'
    | '/onboarding'
    | '/advisory'
    | '/dashboard'
    | '/escrow'
    | '/org'
    | '/login'
    | '/register'
    | '/success'
    | '/verify'
    | '/onboarding/org'
    | '/inbox/ai'
    | '/inbox/nnarks-ai'
    | '/organization/team'
    | '/projects/$projectId'
    | '/vendor/login'
    | '/vendor/register'
    | '/vendor/verify'
    | '/companies/invitations/accept'
    | '/circles'
    | '/inbox'
    | '/organization'
    | '/projects'
    | '/onboarding/account-type'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/built-for'
    | '/contact'
    | '/faqs'
    | '/features'
    | '/financials'
    | '/modules'
    | '/onboarding'
    | '/_app/advisory'
    | '/_app/dashboard'
    | '/_app/escrow'
    | '/_app/inbox'
    | '/_app/org'
    | '/_app/organization'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/success'
    | '/_auth/verify'
    | '/onboarding/org'
    | '/_app/inbox/ai'
    | '/_app/inbox/nnarks-ai'
    | '/_app/organization/team'
    | '/_app/projects/$projectId'
    | '/_auth/vendor/login'
    | '/_auth/vendor/register'
    | '/_auth/vendor/verify'
    | '/companies/invitations/accept'
    | '/_app/circles/'
    | '/_app/inbox/'
    | '/_app/organization/'
    | '/_app/projects/'
    | '/onboarding/account-type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  BuiltForRoute: typeof BuiltForRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  FeaturesRoute: typeof FeaturesRoute
  FinancialsRoute: typeof FinancialsRoute
  ModulesRoute: typeof ModulesRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  CompaniesInvitationsAcceptRoute: typeof CompaniesInvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built-for': {
      id: '/built-for'
      path: '/built-for'
      fullPath: '/built-for'
      preLoaderRoute: typeof BuiltForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/org': {
      id: '/onboarding/org'
      path: '/org'
      fullPath: '/onboarding/org'
      preLoaderRoute: typeof OnboardingOrgRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/success': {
      id: '/_auth/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org': {
      id: '/_app/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escrow': {
      id: '/_app/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof AppEscrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisory': {
      id: '/_app/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AppAdvisoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/account-type/': {
      id: '/onboarding/account-type/'
      path: '/account-type'
      fullPath: '/onboarding/account-type/'
      preLoaderRoute: typeof OnboardingAccountTypeIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/circles/': {
      id: '/_app/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AppCirclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/companies/invitations/accept': {
      id: '/companies/invitations/accept'
      path: '/companies/invitations/accept'
      fullPath: '/companies/invitations/accept'
      preLoaderRoute: typeof CompaniesInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vendor/verify': {
      id: '/_auth/vendor/verify'
      path: '/vendor/verify'
      fullPath: '/vendor/verify'
      preLoaderRoute: typeof AuthVendorVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vendor/register': {
      id: '/_auth/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof AuthVendorRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vendor/login': {
      id: '/_auth/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof AuthVendorLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/team': {
      id: '/_app/organization/team'
      path: '/team'
      fullPath: '/organization/team'
      preLoaderRoute: typeof AppOrganizationTeamRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/inbox/nnarks-ai': {
      id: '/_app/inbox/nnarks-ai'
      path: '/nnarks-ai'
      fullPath: '/inbox/nnarks-ai'
      preLoaderRoute: typeof AppInboxNnarksAiRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/inbox/ai': {
      id: '/_app/inbox/ai'
      path: '/ai'
      fullPath: '/inbox/ai'
      preLoaderRoute: typeof AppInboxAiRouteImport
      parentRoute: typeof AppInboxRoute
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxAiRoute: typeof AppInboxAiRoute
  AppInboxNnarksAiRoute: typeof AppInboxNnarksAiRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxAiRoute: AppInboxAiRoute,
  AppInboxNnarksAiRoute: AppInboxNnarksAiRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppOrganizationRouteChildren {
  AppOrganizationTeamRoute: typeof AppOrganizationTeamRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
}

const AppOrganizationRouteChildren: AppOrganizationRouteChildren = {
  AppOrganizationTeamRoute: AppOrganizationTeamRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
}

const AppOrganizationRouteWithChildren = AppOrganizationRoute._addFileChildren(
  AppOrganizationRouteChildren,
)

interface AppRouteChildren {
  AppAdvisoryRoute: typeof AppAdvisoryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscrowRoute: typeof AppEscrowRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppOrgRoute: typeof AppOrgRoute
  AppOrganizationRoute: typeof AppOrganizationRouteWithChildren
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppCirclesIndexRoute: typeof AppCirclesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisoryRoute: AppAdvisoryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscrowRoute: AppEscrowRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppOrgRoute: AppOrgRoute,
  AppOrganizationRoute: AppOrganizationRouteWithChildren,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppCirclesIndexRoute: AppCirclesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVendorLoginRoute: typeof AuthVendorLoginRoute
  AuthVendorRegisterRoute: typeof AuthVendorRegisterRoute
  AuthVendorVerifyRoute: typeof AuthVendorVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVendorLoginRoute: AuthVendorLoginRoute,
  AuthVendorRegisterRoute: AuthVendorRegisterRoute,
  AuthVendorVerifyRoute: AuthVendorVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingOrgRoute: typeof OnboardingOrgRoute
  OnboardingAccountTypeIndexRoute: typeof OnboardingAccountTypeIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOrgRoute: OnboardingOrgRoute,
  OnboardingAccountTypeIndexRoute: OnboardingAccountTypeIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  BuiltForRoute: BuiltForRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  FeaturesRoute: FeaturesRoute,
  FinancialsRoute: FinancialsRoute,
  ModulesRoute: ModulesRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  CompaniesInvitationsAcceptRoute: CompaniesInvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
