/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuiltForRouteImport } from './routes/built-for'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingVendorRouteImport } from './routes/_onboarding/vendor'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSuccessRouteImport } from './routes/_auth/success'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppEscrowRouteImport } from './routes/_app/escrow'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdvisoryRouteImport } from './routes/_app/advisory'
import { Route as OnboardingAccountTypeIndexRouteImport } from './routes/_onboarding/account-type/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppCirclesIndexRouteImport } from './routes/_app/circles/index'
import { Route as AuthVendorVerifyRouteImport } from './routes/_auth/vendor/verify'
import { Route as AuthVendorRegisterRouteImport } from './routes/_auth/vendor/register'
import { Route as AuthVendorLoginRouteImport } from './routes/_auth/vendor/login'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'

const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/modules.lazy').then((d) => d.Route))
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/financials.lazy').then((d) => d.Route))
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/features.lazy').then((d) => d.Route))
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faqs.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const BuiltForRoute = BuiltForRouteImport.update({
  id: '/built-for',
  path: '/built-for',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/built-for.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVendorRoute = OnboardingVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppEscrowRoute = AppEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisoryRoute = AppAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingAccountTypeIndexRoute =
  OnboardingAccountTypeIndexRouteImport.update({
    id: '/account-type/',
    path: '/account-type/',
    getParentRoute: () => OnboardingRoute,
  } as any).lazy(() =>
    import('./routes/_onboarding/account-type/index.lazy').then((d) => d.Route),
  )
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesIndexRoute = AppCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVendorVerifyRoute = AuthVendorVerifyRouteImport.update({
  id: '/vendor/verify',
  path: '/vendor/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVendorRegisterRoute = AuthVendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVendorLoginRoute = AuthVendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-for': typeof BuiltForRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/financials': typeof FinancialsRoute
  '/modules': typeof ModulesRoute
  '/advisory': typeof AppAdvisoryRoute
  '/dashboard': typeof AppDashboardRoute
  '/escrow': typeof AppEscrowRoute
  '/inbox': typeof AppInboxRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/success': typeof AuthSuccessRoute
  '/verify': typeof AuthVerifyRoute
  '/vendor': typeof OnboardingVendorRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/vendor/login': typeof AuthVendorLoginRoute
  '/vendor/register': typeof AuthVendorRegisterRoute
  '/vendor/verify': typeof AuthVendorVerifyRoute
  '/circles/': typeof AppCirclesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/account-type/': typeof OnboardingAccountTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-for': typeof BuiltForRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/financials': typeof FinancialsRoute
  '/modules': typeof ModulesRoute
  '/advisory': typeof AppAdvisoryRoute
  '/dashboard': typeof AppDashboardRoute
  '/escrow': typeof AppEscrowRoute
  '/inbox': typeof AppInboxRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/success': typeof AuthSuccessRoute
  '/verify': typeof AuthVerifyRoute
  '/vendor': typeof OnboardingVendorRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/vendor/login': typeof AuthVendorLoginRoute
  '/vendor/register': typeof AuthVendorRegisterRoute
  '/vendor/verify': typeof AuthVendorVerifyRoute
  '/circles': typeof AppCirclesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/account-type': typeof OnboardingAccountTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/about': typeof AboutRoute
  '/built-for': typeof BuiltForRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/financials': typeof FinancialsRoute
  '/modules': typeof ModulesRoute
  '/_app/advisory': typeof AppAdvisoryRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escrow': typeof AppEscrowRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/success': typeof AuthSuccessRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_onboarding/vendor': typeof OnboardingVendorRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_auth/vendor/login': typeof AuthVendorLoginRoute
  '/_auth/vendor/register': typeof AuthVendorRegisterRoute
  '/_auth/vendor/verify': typeof AuthVendorVerifyRoute
  '/_app/circles/': typeof AppCirclesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_onboarding/account-type/': typeof OnboardingAccountTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/built-for'
    | '/contact'
    | '/faqs'
    | '/features'
    | '/financials'
    | '/modules'
    | '/advisory'
    | '/dashboard'
    | '/escrow'
    | '/inbox'
    | '/login'
    | '/register'
    | '/success'
    | '/verify'
    | '/vendor'
    | '/projects/$projectId'
    | '/vendor/login'
    | '/vendor/register'
    | '/vendor/verify'
    | '/circles/'
    | '/projects/'
    | '/account-type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/built-for'
    | '/contact'
    | '/faqs'
    | '/features'
    | '/financials'
    | '/modules'
    | '/advisory'
    | '/dashboard'
    | '/escrow'
    | '/inbox'
    | '/login'
    | '/register'
    | '/success'
    | '/verify'
    | '/vendor'
    | '/projects/$projectId'
    | '/vendor/login'
    | '/vendor/register'
    | '/vendor/verify'
    | '/circles'
    | '/projects'
    | '/account-type'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_onboarding'
    | '/about'
    | '/built-for'
    | '/contact'
    | '/faqs'
    | '/features'
    | '/financials'
    | '/modules'
    | '/_app/advisory'
    | '/_app/dashboard'
    | '/_app/escrow'
    | '/_app/inbox'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/success'
    | '/_auth/verify'
    | '/_onboarding/vendor'
    | '/_app/projects/$projectId'
    | '/_auth/vendor/login'
    | '/_auth/vendor/register'
    | '/_auth/vendor/verify'
    | '/_app/circles/'
    | '/_app/projects/'
    | '/_onboarding/account-type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  AboutRoute: typeof AboutRoute
  BuiltForRoute: typeof BuiltForRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  FeaturesRoute: typeof FeaturesRoute
  FinancialsRoute: typeof FinancialsRoute
  ModulesRoute: typeof ModulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built-for': {
      id: '/built-for'
      path: '/built-for'
      fullPath: '/built-for'
      preLoaderRoute: typeof BuiltForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/vendor': {
      id: '/_onboarding/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof OnboardingVendorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/success': {
      id: '/_auth/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escrow': {
      id: '/_app/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof AppEscrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisory': {
      id: '/_app/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AppAdvisoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_onboarding/account-type/': {
      id: '/_onboarding/account-type/'
      path: '/account-type'
      fullPath: '/account-type/'
      preLoaderRoute: typeof OnboardingAccountTypeIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/': {
      id: '/_app/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AppCirclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/vendor/verify': {
      id: '/_auth/vendor/verify'
      path: '/vendor/verify'
      fullPath: '/vendor/verify'
      preLoaderRoute: typeof AuthVendorVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vendor/register': {
      id: '/_auth/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof AuthVendorRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vendor/login': {
      id: '/_auth/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof AuthVendorLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvisoryRoute: typeof AppAdvisoryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscrowRoute: typeof AppEscrowRoute
  AppInboxRoute: typeof AppInboxRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppCirclesIndexRoute: typeof AppCirclesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisoryRoute: AppAdvisoryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscrowRoute: AppEscrowRoute,
  AppInboxRoute: AppInboxRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppCirclesIndexRoute: AppCirclesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVendorLoginRoute: typeof AuthVendorLoginRoute
  AuthVendorRegisterRoute: typeof AuthVendorRegisterRoute
  AuthVendorVerifyRoute: typeof AuthVendorVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVendorLoginRoute: AuthVendorLoginRoute,
  AuthVendorRegisterRoute: AuthVendorRegisterRoute,
  AuthVendorVerifyRoute: AuthVendorVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingVendorRoute: typeof OnboardingVendorRoute
  OnboardingAccountTypeIndexRoute: typeof OnboardingAccountTypeIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingVendorRoute: OnboardingVendorRoute,
  OnboardingAccountTypeIndexRoute: OnboardingAccountTypeIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  AboutRoute: AboutRoute,
  BuiltForRoute: BuiltForRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  FeaturesRoute: FeaturesRoute,
  FinancialsRoute: FinancialsRoute,
  ModulesRoute: ModulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
